Traceback (most recent call last):
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\core\management\base.py", line 417, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 70, in execute
    super().execute(*args, **options)
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\core\management\base.py", line 461, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 81, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
           ^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\conf\__init__.py", line 167, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core.settings_maintenance '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\bakim_kalibrasyon\manage.py", line 26, in <module>
    main()
  File "C:\dev\bakim_kalibrasyon\manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\core\management\__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\core\management\__init__.py", line 437, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\core\management\base.py", line 430, in run_from_argv
    connections.close_all()
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\utils\connection.py", line 85, in close_all
    for conn in self.all(initialized_only=True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\utils\connection.py", line 77, in all
    return [
           ^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\utils\connection.py", line 74, in __iter__
    return iter(self.settings)
                ^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\utils\connection.py", line 46, in settings
    self._settings = self.configure_settings(self._settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\db\utils.py", line 149, in configure_settings
    databases = super().configure_settings(databases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\utils\connection.py", line 51, in configure_settings
    settings = getattr(django_settings, self.settings_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\bakim_kalibrasyon\venv\Lib\site-packages\django\conf\__init__.py", line 167, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core.settings_maintenance '
